# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpacyGUI\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1392, 1381)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton_init_home = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_init_home.setGeometry(QtCore.QRect(10, 0, 75, 23))
        self.pushButton_init_home.setObjectName("pushButton_init_home")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(190, 10, 581, 271))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_text_file_input_dir_XML = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_text_file_input_dir_XML.setGeometry(QtCore.QRect(160, 30, 251, 20))
        self.lineEdit_text_file_input_dir_XML.setObjectName("lineEdit_text_file_input_dir_XML")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(50, 30, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 190, 91, 16))
        self.label.setObjectName("label")
        self.lineEdit_text_file_input_dir_TXT = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_text_file_input_dir_TXT.setGeometry(QtCore.QRect(160, 190, 251, 20))
        self.lineEdit_text_file_input_dir_TXT.setObjectName("lineEdit_text_file_input_dir_TXT")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(180, 60, 20, 121))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.line.setFont(font)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.checkBox_prepro_abstract = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_prepro_abstract.setGeometry(QtCore.QRect(230, 70, 70, 17))
        self.checkBox_prepro_abstract.setObjectName("checkBox_prepro_abstract")
        self.checkBox_prepro_introduction = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_prepro_introduction.setGeometry(QtCore.QRect(230, 90, 81, 17))
        self.checkBox_prepro_introduction.setChecked(True)
        self.checkBox_prepro_introduction.setObjectName("checkBox_prepro_introduction")
        self.checkBox_prepro_methods = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_prepro_methods.setGeometry(QtCore.QRect(230, 110, 70, 17))
        self.checkBox_prepro_methods.setObjectName("checkBox_prepro_methods")
        self.checkBox_prepro_results = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_prepro_results.setGeometry(QtCore.QRect(230, 130, 70, 17))
        self.checkBox_prepro_results.setObjectName("checkBox_prepro_results")
        self.checkBox_prepro_discussion = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_prepro_discussion.setGeometry(QtCore.QRect(230, 150, 70, 17))
        self.checkBox_prepro_discussion.setObjectName("checkBox_prepro_discussion")
        self.checkBox_prepro_conclusion = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_prepro_conclusion.setGeometry(QtCore.QRect(230, 170, 70, 17))
        self.checkBox_prepro_conclusion.setObjectName("checkBox_prepro_conclusion")
        self.pushButton_preprocess = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_preprocess.setGeometry(QtCore.QRect(440, 190, 75, 23))
        self.pushButton_preprocess.setObjectName("pushButton_preprocess")
        self.lineEdit_drugs_pattern_jsonl = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_drugs_pattern_jsonl.setGeometry(QtCore.QRect(20, 240, 271, 20))
        self.lineEdit_drugs_pattern_jsonl.setObjectName("lineEdit_drugs_pattern_jsonl")
        self.pushButton_add_drug_patterns_before_ner = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_add_drug_patterns_before_ner.setGeometry(QtCore.QRect(320, 240, 251, 23))
        self.pushButton_add_drug_patterns_before_ner.setObjectName("pushButton_add_drug_patterns_before_ner")
        self.lineEdit_text_file_output_dir = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_text_file_output_dir.setGeometry(QtCore.QRect(210, 1280, 251, 20))
        self.lineEdit_text_file_output_dir.setObjectName("lineEdit_text_file_output_dir")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(100, 1280, 91, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_init_work = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_init_work.setGeometry(QtCore.QRect(90, 0, 75, 23))
        self.pushButton_init_work.setObjectName("pushButton_init_work")
        self.textEdit_ent_sentence = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_ent_sentence.setGeometry(QtCore.QRect(50, 510, 1321, 91))
        self.textEdit_ent_sentence.setObjectName("textEdit_ent_sentence")
        self.pushButton_get_next_sentence = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_get_next_sentence.setGeometry(QtCore.QRect(1090, 610, 291, 23))
        self.pushButton_get_next_sentence.setObjectName("pushButton_get_next_sentence")
        self.pushButton_test = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_test.setGeometry(QtCore.QRect(860, 1250, 75, 23))
        self.pushButton_test.setObjectName("pushButton_test")
        self.textEdit_original_sentence = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_original_sentence.setGeometry(QtCore.QRect(40, 280, 1321, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_original_sentence.setFont(font)
        self.textEdit_original_sentence.setObjectName("textEdit_original_sentence")
        self.textEdit_entities = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_entities.setGeometry(QtCore.QRect(950, 10, 351, 211))
        self.textEdit_entities.setObjectName("textEdit_entities")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(700, 920, 681, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit_pattern = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_pattern.setGeometry(QtCore.QRect(30, 60, 591, 51))
        self.textEdit_pattern.setObjectName("textEdit_pattern")
        self.pushButton_add_pattern = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_add_pattern.setGeometry(QtCore.QRect(220, 120, 131, 23))
        self.pushButton_add_pattern.setObjectName("pushButton_add_pattern")
        self.lineEdit_file_to_save_patterns = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_file_to_save_patterns.setGeometry(QtCore.QRect(160, 20, 391, 20))
        self.lineEdit_file_to_save_patterns.setObjectName("lineEdit_file_to_save_patterns")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 111, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_add_pattern_reintegrate = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_add_pattern_reintegrate.setGeometry(QtCore.QRect(370, 120, 281, 23))
        self.pushButton_add_pattern_reintegrate.setObjectName("pushButton_add_pattern_reintegrate")
        self.TRAIN_DATA = QtWidgets.QGroupBox(self.centralWidget)
        self.TRAIN_DATA.setGeometry(QtCore.QRect(40, 630, 1321, 211))
        self.TRAIN_DATA.setObjectName("TRAIN_DATA")
        self.textEdit_TRAIN_DATA_sentences = QtWidgets.QTextEdit(self.TRAIN_DATA)
        self.textEdit_TRAIN_DATA_sentences.setGeometry(QtCore.QRect(20, 50, 1281, 101))
        self.textEdit_TRAIN_DATA_sentences.setObjectName("textEdit_TRAIN_DATA_sentences")
        self.pushButton_add_sentence_to_TRAIN_DATA = QtWidgets.QPushButton(self.TRAIN_DATA)
        self.pushButton_add_sentence_to_TRAIN_DATA.setGeometry(QtCore.QRect(954, 170, 191, 23))
        self.pushButton_add_sentence_to_TRAIN_DATA.setObjectName("pushButton_add_sentence_to_TRAIN_DATA")
        self.label_5 = QtWidgets.QLabel(self.TRAIN_DATA)
        self.label_5.setGeometry(QtCore.QRect(60, 20, 191, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_file_to_save_TRAIN_DATA = QtWidgets.QLineEdit(self.TRAIN_DATA)
        self.lineEdit_file_to_save_TRAIN_DATA.setGeometry(QtCore.QRect(350, 20, 391, 20))
        self.lineEdit_file_to_save_TRAIN_DATA.setObjectName("lineEdit_file_to_save_TRAIN_DATA")
        self.listWidget_unknown_words = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget_unknown_words.setGeometry(QtCore.QRect(50, 900, 191, 192))
        self.listWidget_unknown_words.setObjectName("listWidget_unknown_words")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(60, 860, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.listWidget_entities = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget_entities.setGeometry(QtCore.QRect(270, 900, 151, 271))
        self.listWidget_entities.setObjectName("listWidget_entities")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(300, 860, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_auto_create_pattern = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_auto_create_pattern.setGeometry(QtCore.QRect(440, 980, 131, 23))
        self.pushButton_auto_create_pattern.setObjectName("pushButton_auto_create_pattern")
        self.pushButton_save_selected_to_stringstore = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_save_selected_to_stringstore.setGeometry(QtCore.QRect(50, 1150, 191, 23))
        self.pushButton_save_selected_to_stringstore.setObjectName("pushButton_save_selected_to_stringstore")
        self.lineEdit_stringstore_dir = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_stringstore_dir.setGeometry(QtCore.QRect(60, 1110, 181, 20))
        self.lineEdit_stringstore_dir.setObjectName("lineEdit_stringstore_dir")
        self.lineEdit_entity_file = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_entity_file.setGeometry(QtCore.QRect(270, 1180, 151, 20))
        self.lineEdit_entity_file.setObjectName("lineEdit_entity_file")
        self.lineEdit_entity_to_add = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_entity_to_add.setGeometry(QtCore.QRect(310, 1210, 113, 20))
        self.lineEdit_entity_to_add.setObjectName("lineEdit_entity_to_add")
        self.pushButton_add_entity = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_add_entity.setGeometry(QtCore.QRect(430, 1220, 75, 23))
        self.pushButton_add_entity.setObjectName("pushButton_add_entity")
        self.lineEdit_entity_description_to_add = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_entity_description_to_add.setGeometry(QtCore.QRect(272, 1240, 151, 20))
        self.lineEdit_entity_description_to_add.setObjectName("lineEdit_entity_description_to_add")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(240, 1210, 61, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(200, 1240, 61, 20))
        self.label_9.setObjectName("label_9")
        self.pushButton_add_stringstore_temporarly_to_vocab = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_add_stringstore_temporarly_to_vocab.setGeometry(QtCore.QRect(50, 1180, 191, 23))
        self.pushButton_add_stringstore_temporarly_to_vocab.setObjectName("pushButton_add_stringstore_temporarly_to_vocab")
        self.pushButton_auto_train_pattern_from_selection = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_auto_train_pattern_from_selection.setGeometry(QtCore.QRect(680, 610, 311, 23))
        self.pushButton_auto_train_pattern_from_selection.setObjectName("pushButton_auto_train_pattern_from_selection")
        self.checkBox_lower = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_lower.setGeometry(QtCore.QRect(450, 900, 70, 17))
        self.checkBox_lower.setChecked(True)
        self.checkBox_lower.setObjectName("checkBox_lower")
        self.textEdit_alt_text_sentence = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_alt_text_sentence.setGeometry(QtCore.QRect(40, 350, 1321, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_alt_text_sentence.setFont(font)
        self.textEdit_alt_text_sentence.setObjectName("textEdit_alt_text_sentence")
        self.textEdit_token_sentence = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_token_sentence.setGeometry(QtCore.QRect(40, 430, 1321, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_token_sentence.setFont(font)
        self.textEdit_token_sentence.setObjectName("textEdit_token_sentence")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(10, 420, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(10, 340, 47, 13))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_12.setGeometry(QtCore.QRect(20, 260, 47, 13))
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1392, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_init_home.setText(_translate("MainWindow", "init home"))
        self.groupBox.setTitle(_translate("MainWindow", "Extract Text from XML File"))
        self.lineEdit_text_file_input_dir_XML.setText(_translate("MainWindow", "G:\\Daten\\Elsevir_paper\\XMLJSON"))
        self.label_3.setText(_translate("MainWindow", "XML file Input dir"))
        self.label.setText(_translate("MainWindow", "Text file Input dir"))
        self.lineEdit_text_file_input_dir_TXT.setText(_translate("MainWindow", "G:\\Daten\\Elsevir_paper\\TXT_extract"))
        self.checkBox_prepro_abstract.setText(_translate("MainWindow", "Abstract"))
        self.checkBox_prepro_introduction.setText(_translate("MainWindow", "Introduction"))
        self.checkBox_prepro_methods.setText(_translate("MainWindow", "Methods"))
        self.checkBox_prepro_results.setText(_translate("MainWindow", "Results"))
        self.checkBox_prepro_discussion.setText(_translate("MainWindow", "Discussion"))
        self.checkBox_prepro_conclusion.setText(_translate("MainWindow", "Conclusion"))
        self.pushButton_preprocess.setText(_translate("MainWindow", "preprocess"))
        self.lineEdit_drugs_pattern_jsonl.setText(_translate("MainWindow", "G:\\OneDrive\\Python\\SpacyEditor\\Lib\\drugs_FDA_lower.jsonl"))
        self.pushButton_add_drug_patterns_before_ner.setText(_translate("MainWindow", "add drug patters before ner"))
        self.lineEdit_text_file_output_dir.setText(_translate("MainWindow", "G:\\Daten\\Elsevir_paper\\Spacy_prepro"))
        self.label_2.setText(_translate("MainWindow", "Spacy file Output dir"))
        self.pushButton_init_work.setText(_translate("MainWindow", "init work"))
        self.pushButton_get_next_sentence.setText(_translate("MainWindow", "get next sentence"))
        self.pushButton_test.setText(_translate("MainWindow", "test"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Pattern Creator"))
        self.textEdit_pattern.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> [{\'label\': \'GPE\', \'pattern\': [{\'lower\': \'san\'}, {\'lower\': \'francisco\'}]}]</p></body></html>"))
        self.pushButton_add_pattern.setText(_translate("MainWindow", "add pattern to library"))
        self.lineEdit_file_to_save_patterns.setText(_translate("MainWindow", "./patterns.jsonl"))
        self.label_4.setText(_translate("MainWindow", "file to save patterns"))
        self.pushButton_add_pattern_reintegrate.setText(_translate("MainWindow", "integrate current library to spacy pipeline before ner"))
        self.TRAIN_DATA.setTitle(_translate("MainWindow", "TRAIN_DATA"))
        self.pushButton_add_sentence_to_TRAIN_DATA.setText(_translate("MainWindow", "add Sentence to TRAIN_DATA"))
        self.label_5.setText(_translate("MainWindow", "file to save TRAIN_DATA sentences"))
        self.lineEdit_file_to_save_TRAIN_DATA.setText(_translate("MainWindow", "./TRAIN_DATA01.txt"))
        self.label_6.setText(_translate("MainWindow", "Unknown Words"))
        self.label_7.setText(_translate("MainWindow", "Entities"))
        self.pushButton_auto_create_pattern.setText(_translate("MainWindow", "auto create pattern--->"))
        self.pushButton_save_selected_to_stringstore.setText(_translate("MainWindow", "save selected to StringStore"))
        self.lineEdit_stringstore_dir.setText(_translate("MainWindow", "./stringstore"))
        self.lineEdit_entity_file.setText(_translate("MainWindow", "./entities.json"))
        self.pushButton_add_entity.setText(_translate("MainWindow", "add entity"))
        self.label_8.setText(_translate("MainWindow", "Entity name"))
        self.label_9.setText(_translate("MainWindow", "Description"))
        self.pushButton_add_stringstore_temporarly_to_vocab.setText(_translate("MainWindow", "add temporarely StringStore to vocab"))
        self.pushButton_auto_train_pattern_from_selection.setText(_translate("MainWindow", "Selection + Entity to TrainSentence and Pattern"))
        self.checkBox_lower.setText(_translate("MainWindow", "LOWER"))
        self.label_10.setText(_translate("MainWindow", "Token"))
        self.label_11.setText(_translate("MainWindow", "alt text"))
        self.label_12.setText(_translate("MainWindow", "org text"))


